// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server/priv/config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from server/priv/config.proto</summary>
public static partial class ConfigReflection {

  #region Descriptor
  /// <summary>File descriptor for server/priv/config.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ConfigReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhzZXJ2ZXIvcHJpdi9jb25maWcucHJvdG8inwEKBEdhbWUSDQoFd2lkdGgY",
          "ASABKAQSDgoGaGVpZ2h0GAIgASgEEi8KEG1hcF9tb2RpZmljYXRpb24YAyAB",
          "KAsyEC5NYXBNb2RpZmljYXRpb25IAIgBARIdChBsb290X2ludGVydmFsX21z",
          "GAQgASgESAGIAQFCEwoRX21hcF9tb2RpZmljYXRpb25CEwoRX2xvb3RfaW50",
          "ZXJ2YWxfbXMiugEKD01hcE1vZGlmaWNhdGlvbhIjCgxtb2RpZmljYXRpb24Y",
          "ASABKAsyDS5Nb2RpZmljYXRpb24SFwoPc3RhcnRpbmdfcmFkaXVzGAIgASgE",
          "EhYKDm1pbmltdW1fcmFkaXVzGAMgASgEEhIKCm1heF9yYWRpdXMYBCABKAQS",
          "HgoWb3V0c2lkZV9yYWRpdXNfZWZmZWN0cxgFIAMoCRIdChVpbnNpZGVfcmFk",
          "aXVzX2VmZmVjdHMYBiADKAkiLwoMTW9kaWZpY2F0aW9uEhAKCG1vZGlmaWVy",
          "GAEgASgJEg0KBXZhbHVlGAIgASgDYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Game), global::Game.Parser, new[]{ "Width", "Height", "MapModification", "LootIntervalMs" }, new[]{ "MapModification", "LootIntervalMs" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MapModification), global::MapModification.Parser, new[]{ "Modification", "StartingRadius", "MinimumRadius", "MaxRadius", "OutsideRadiusEffects", "InsideRadiusEffects" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Modification), global::Modification.Parser, new[]{ "Modifier", "Value" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Represents the initial game state.
///- width: The width of the playing area.
///- height: The length of the playing area.
///- map_modification: If present, contains the information for when the map modification mechanic is triggered
///- loot_interval_ms: If present, interval in milliseconds for spawning loot crates
/// </summary>
public sealed partial class Game : pb::IMessage<Game>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Game> _parser = new pb::MessageParser<Game>(() => new Game());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Game> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfigReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Game() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Game(Game other) : this() {
    _hasBits0 = other._hasBits0;
    width_ = other.width_;
    height_ = other.height_;
    mapModification_ = other.mapModification_ != null ? other.mapModification_.Clone() : null;
    lootIntervalMs_ = other.lootIntervalMs_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Game Clone() {
    return new Game(this);
  }

  /// <summary>Field number for the "width" field.</summary>
  public const int WidthFieldNumber = 1;
  private ulong width_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Width {
    get { return width_; }
    set {
      width_ = value;
    }
  }

  /// <summary>Field number for the "height" field.</summary>
  public const int HeightFieldNumber = 2;
  private ulong height_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Height {
    get { return height_; }
    set {
      height_ = value;
    }
  }

  /// <summary>Field number for the "map_modification" field.</summary>
  public const int MapModificationFieldNumber = 3;
  private global::MapModification mapModification_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MapModification MapModification {
    get { return mapModification_; }
    set {
      mapModification_ = value;
    }
  }

  /// <summary>Field number for the "loot_interval_ms" field.</summary>
  public const int LootIntervalMsFieldNumber = 4;
  private ulong lootIntervalMs_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong LootIntervalMs {
    get { if ((_hasBits0 & 1) != 0) { return lootIntervalMs_; } else { return 0UL; } }
    set {
      _hasBits0 |= 1;
      lootIntervalMs_ = value;
    }
  }
  /// <summary>Gets whether the "loot_interval_ms" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLootIntervalMs {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "loot_interval_ms" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLootIntervalMs() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Game);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Game other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Width != other.Width) return false;
    if (Height != other.Height) return false;
    if (!object.Equals(MapModification, other.MapModification)) return false;
    if (LootIntervalMs != other.LootIntervalMs) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Width != 0UL) hash ^= Width.GetHashCode();
    if (Height != 0UL) hash ^= Height.GetHashCode();
    if (mapModification_ != null) hash ^= MapModification.GetHashCode();
    if (HasLootIntervalMs) hash ^= LootIntervalMs.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Width != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Width);
    }
    if (Height != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Height);
    }
    if (mapModification_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(MapModification);
    }
    if (HasLootIntervalMs) {
      output.WriteRawTag(32);
      output.WriteUInt64(LootIntervalMs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Width != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Width);
    }
    if (Height != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Height);
    }
    if (mapModification_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(MapModification);
    }
    if (HasLootIntervalMs) {
      output.WriteRawTag(32);
      output.WriteUInt64(LootIntervalMs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Width != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Width);
    }
    if (Height != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Height);
    }
    if (mapModification_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapModification);
    }
    if (HasLootIntervalMs) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LootIntervalMs);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Game other) {
    if (other == null) {
      return;
    }
    if (other.Width != 0UL) {
      Width = other.Width;
    }
    if (other.Height != 0UL) {
      Height = other.Height;
    }
    if (other.mapModification_ != null) {
      if (mapModification_ == null) {
        MapModification = new global::MapModification();
      }
      MapModification.MergeFrom(other.MapModification);
    }
    if (other.HasLootIntervalMs) {
      LootIntervalMs = other.LootIntervalMs;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Width = input.ReadUInt64();
          break;
        }
        case 16: {
          Height = input.ReadUInt64();
          break;
        }
        case 26: {
          if (mapModification_ == null) {
            MapModification = new global::MapModification();
          }
          input.ReadMessage(MapModification);
          break;
        }
        case 32: {
          LootIntervalMs = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Width = input.ReadUInt64();
          break;
        }
        case 16: {
          Height = input.ReadUInt64();
          break;
        }
        case 26: {
          if (mapModification_ == null) {
            MapModification = new global::MapModification();
          }
          input.ReadMessage(MapModification);
          break;
        }
        case 32: {
          LootIntervalMs = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// The information for when the map modification mechanic is triggered.
///- modification: Defines how to modify the playable area radius.
///- starting_radius: Starting radius for the playable area.
///- minimum_radius: Mininum radius for the playable area, how small can the playable zone get.
///- max_radius: Max radius for the playable area, how big can the playable zone get.
///- outside_radius_effects: Effects given when a player is outside the playable area.
///- inside_radius_effects: Effects given when a player is inside the playable area.
/// </summary>
public sealed partial class MapModification : pb::IMessage<MapModification>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MapModification> _parser = new pb::MessageParser<MapModification>(() => new MapModification());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MapModification> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfigReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MapModification() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MapModification(MapModification other) : this() {
    modification_ = other.modification_ != null ? other.modification_.Clone() : null;
    startingRadius_ = other.startingRadius_;
    minimumRadius_ = other.minimumRadius_;
    maxRadius_ = other.maxRadius_;
    outsideRadiusEffects_ = other.outsideRadiusEffects_.Clone();
    insideRadiusEffects_ = other.insideRadiusEffects_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MapModification Clone() {
    return new MapModification(this);
  }

  /// <summary>Field number for the "modification" field.</summary>
  public const int ModificationFieldNumber = 1;
  private global::Modification modification_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Modification Modification {
    get { return modification_; }
    set {
      modification_ = value;
    }
  }

  /// <summary>Field number for the "starting_radius" field.</summary>
  public const int StartingRadiusFieldNumber = 2;
  private ulong startingRadius_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong StartingRadius {
    get { return startingRadius_; }
    set {
      startingRadius_ = value;
    }
  }

  /// <summary>Field number for the "minimum_radius" field.</summary>
  public const int MinimumRadiusFieldNumber = 3;
  private ulong minimumRadius_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong MinimumRadius {
    get { return minimumRadius_; }
    set {
      minimumRadius_ = value;
    }
  }

  /// <summary>Field number for the "max_radius" field.</summary>
  public const int MaxRadiusFieldNumber = 4;
  private ulong maxRadius_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong MaxRadius {
    get { return maxRadius_; }
    set {
      maxRadius_ = value;
    }
  }

  /// <summary>Field number for the "outside_radius_effects" field.</summary>
  public const int OutsideRadiusEffectsFieldNumber = 5;
  private static readonly pb::FieldCodec<string> _repeated_outsideRadiusEffects_codec
      = pb::FieldCodec.ForString(42);
  private readonly pbc::RepeatedField<string> outsideRadiusEffects_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> OutsideRadiusEffects {
    get { return outsideRadiusEffects_; }
  }

  /// <summary>Field number for the "inside_radius_effects" field.</summary>
  public const int InsideRadiusEffectsFieldNumber = 6;
  private static readonly pb::FieldCodec<string> _repeated_insideRadiusEffects_codec
      = pb::FieldCodec.ForString(50);
  private readonly pbc::RepeatedField<string> insideRadiusEffects_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> InsideRadiusEffects {
    get { return insideRadiusEffects_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MapModification);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MapModification other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Modification, other.Modification)) return false;
    if (StartingRadius != other.StartingRadius) return false;
    if (MinimumRadius != other.MinimumRadius) return false;
    if (MaxRadius != other.MaxRadius) return false;
    if(!outsideRadiusEffects_.Equals(other.outsideRadiusEffects_)) return false;
    if(!insideRadiusEffects_.Equals(other.insideRadiusEffects_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (modification_ != null) hash ^= Modification.GetHashCode();
    if (StartingRadius != 0UL) hash ^= StartingRadius.GetHashCode();
    if (MinimumRadius != 0UL) hash ^= MinimumRadius.GetHashCode();
    if (MaxRadius != 0UL) hash ^= MaxRadius.GetHashCode();
    hash ^= outsideRadiusEffects_.GetHashCode();
    hash ^= insideRadiusEffects_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (modification_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Modification);
    }
    if (StartingRadius != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(StartingRadius);
    }
    if (MinimumRadius != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(MinimumRadius);
    }
    if (MaxRadius != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(MaxRadius);
    }
    outsideRadiusEffects_.WriteTo(output, _repeated_outsideRadiusEffects_codec);
    insideRadiusEffects_.WriteTo(output, _repeated_insideRadiusEffects_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (modification_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Modification);
    }
    if (StartingRadius != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(StartingRadius);
    }
    if (MinimumRadius != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(MinimumRadius);
    }
    if (MaxRadius != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(MaxRadius);
    }
    outsideRadiusEffects_.WriteTo(ref output, _repeated_outsideRadiusEffects_codec);
    insideRadiusEffects_.WriteTo(ref output, _repeated_insideRadiusEffects_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (modification_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Modification);
    }
    if (StartingRadius != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartingRadius);
    }
    if (MinimumRadius != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MinimumRadius);
    }
    if (MaxRadius != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MaxRadius);
    }
    size += outsideRadiusEffects_.CalculateSize(_repeated_outsideRadiusEffects_codec);
    size += insideRadiusEffects_.CalculateSize(_repeated_insideRadiusEffects_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MapModification other) {
    if (other == null) {
      return;
    }
    if (other.modification_ != null) {
      if (modification_ == null) {
        Modification = new global::Modification();
      }
      Modification.MergeFrom(other.Modification);
    }
    if (other.StartingRadius != 0UL) {
      StartingRadius = other.StartingRadius;
    }
    if (other.MinimumRadius != 0UL) {
      MinimumRadius = other.MinimumRadius;
    }
    if (other.MaxRadius != 0UL) {
      MaxRadius = other.MaxRadius;
    }
    outsideRadiusEffects_.Add(other.outsideRadiusEffects_);
    insideRadiusEffects_.Add(other.insideRadiusEffects_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (modification_ == null) {
            Modification = new global::Modification();
          }
          input.ReadMessage(Modification);
          break;
        }
        case 16: {
          StartingRadius = input.ReadUInt64();
          break;
        }
        case 24: {
          MinimumRadius = input.ReadUInt64();
          break;
        }
        case 32: {
          MaxRadius = input.ReadUInt64();
          break;
        }
        case 42: {
          outsideRadiusEffects_.AddEntriesFrom(input, _repeated_outsideRadiusEffects_codec);
          break;
        }
        case 50: {
          insideRadiusEffects_.AddEntriesFrom(input, _repeated_insideRadiusEffects_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (modification_ == null) {
            Modification = new global::Modification();
          }
          input.ReadMessage(Modification);
          break;
        }
        case 16: {
          StartingRadius = input.ReadUInt64();
          break;
        }
        case 24: {
          MinimumRadius = input.ReadUInt64();
          break;
        }
        case 32: {
          MaxRadius = input.ReadUInt64();
          break;
        }
        case 42: {
          outsideRadiusEffects_.AddEntriesFrom(ref input, _repeated_outsideRadiusEffects_codec);
          break;
        }
        case 50: {
          insideRadiusEffects_.AddEntriesFrom(ref input, _repeated_insideRadiusEffects_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Defines how to modify the playable area radius.
///- modifier: Determines how `value` interacts with the current value of the attribute, it can be one of
///- additive: Given value is added to current value
///- multiplicative: Given value is multiplied to current value
///- override: Given value is set as the attribute value
///- value: The value we are using for the changemessage Modification {
/// </summary>
public sealed partial class Modification : pb::IMessage<Modification>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Modification> _parser = new pb::MessageParser<Modification>(() => new Modification());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Modification> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfigReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Modification() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Modification(Modification other) : this() {
    modifier_ = other.modifier_;
    value_ = other.value_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Modification Clone() {
    return new Modification(this);
  }

  /// <summary>Field number for the "modifier" field.</summary>
  public const int ModifierFieldNumber = 1;
  private string modifier_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Modifier {
    get { return modifier_; }
    set {
      modifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 2;
  private long value_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Value {
    get { return value_; }
    set {
      value_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Modification);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Modification other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Modifier != other.Modifier) return false;
    if (Value != other.Value) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Modifier.Length != 0) hash ^= Modifier.GetHashCode();
    if (Value != 0L) hash ^= Value.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Modifier.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Modifier);
    }
    if (Value != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Modifier.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Modifier);
    }
    if (Value != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Modifier.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Modifier);
    }
    if (Value != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Modification other) {
    if (other == null) {
      return;
    }
    if (other.Modifier.Length != 0) {
      Modifier = other.Modifier;
    }
    if (other.Value != 0L) {
      Value = other.Value;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Modifier = input.ReadString();
          break;
        }
        case 16: {
          Value = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Modifier = input.ReadString();
          break;
        }
        case 16: {
          Value = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
